"""
Interactive script to set up database configuration
Creates a .env file with user-provided credentials
"""
import os
from pathlib import Path

def create_env_file():
    """Interactive setup for .env file"""
    print("\n" + "="*80)
    print("DATABASE CONFIGURATION SETUP".center(80))
    print("="*80)
    print("\nThis script will help you create a .env file for database credentials.")
    print("The .env file is git-ignored for security.\n")
    
    # Get project root (parent of scripts folder)
    project_root = Path(__file__).parent.parent
    env_path = project_root / '.env'
    
    # Check if .env already exists
    if env_path.exists():
        overwrite = input("\n.env file already exists. Overwrite? (yes/no): ").strip().lower()
        if overwrite not in ['yes', 'y']:
            print("\nSetup cancelled.")
            return
    
    # Collect credentials
    print("\nEnter your database credentials:")
    print("-" * 80)
    
    db_host = input("Database Host: ").strip()
    db_port = input("Database Port [5432]: ").strip() or "5432"
    db_name = input("Database Name [postgres]: ").strip() or "postgres"
    db_user = input("Database User: ").strip()
    db_password = input("Database Password: ").strip()
    
    # Validate inputs
    if not all([db_host, db_port, db_name, db_user, db_password]):
        print("\n[!] Error: All fields are required.")
        return
    
    # Create .env file
    env_content = f"""# Database Configuration
# Generated by setup_env.py
# NEVER commit this file to git

DB_HOST={db_host}
DB_PORT={db_port}
DB_NAME={db_name}
DB_USER={db_user}
DB_PASSWORD={db_password}
"""
    
    try:
        with open(env_path, 'w') as f:
            f.write(env_content)
        
        print("\n" + "="*80)
        print("[+] SUCCESS! .env file created at:", env_path)
        print("="*80)
        print("\nYour credentials are now securely stored and git-ignored.")
        print("You can now run any database scripts.\n")
        
    except Exception as e:
        print(f"\n[-] Error creating .env file: {e}")

if __name__ == "__main__":
    try:
        create_env_file()
    except KeyboardInterrupt:
        print("\n\n[*] Setup cancelled by user.")

